apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.redisLabel.app }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.redisLabel.app }}

    spec:
      containers:
      - name: {{ .Values.redisContainer.name }}
        image: {{ .Values.redisContainer.image }}
        ports:
        - containerPort: {{ .Values.redisContainer.port }}